import type { Metadata } from 'next';
import { SessionProvider } from 'next-auth/react';
import { Noto_Sans_KR } from 'next/font/google';
import './globals.css';
import Providers from '../components/provider/query-provider';
import { Toaster } from '../components/ui/toaster';
import { getSession } from '@/service/auth/auth';

const notoSansKr = Noto_Sans_KR({
  weight: ['500'],
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getSession();
  return (
    <SessionProvider session={session}>
      <html lang="en" className="h-screen flex flex-col">
        <body className={`${notoSansKr.className} grow`}>
          <Providers>
            <Toaster />
            {children}
          </Providers>
        </body>
      </html>
    </SessionProvider>
  );
}
