import type { Metadata } from 'next';
import { SessionProvider } from 'next-auth/react';
import { Noto_Sans_KR } from 'next/font/google';
import './globals.css';
import { auth } from '@/auth';
import { Toaster } from '@/components/ui/toaster';

const notoSansKr = Noto_Sans_KR({
  weight: ['500'],
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  return (
    <SessionProvider session={session}>
      <html lang="en" className="h-screen flex flex-col">
        <body className={`${notoSansKr.className} grow`}>
          <Toaster />
          {children}
        </body>
      </html>
    </SessionProvider>
  );
}
